# Generated by Django 5.1 on 2025-08-20 00:39

import apps.billing.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_file', models.FileField(upload_to=apps.billing.models.bill_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Enviado'), ('PROCESSING', 'Processando'), ('PROCESSED', 'Processado'), ('FAILED', 'Falhou')], default='UPLOADED', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('parsed_json', models.JSONField(blank=True, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=100)),
                ('numero_cliente', models.CharField(blank=True, max_length=50)),
                ('unidade_consumidora', models.CharField(blank=True, max_length=50)),
                ('instalacao', models.CharField(blank=True, max_length=50)),
                ('endereco', models.TextField(blank=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('consumo_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tarifa_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bandeira_tarifaria', models.CharField(choices=[('VERDE', 'Verde'), ('AMARELA', 'Amarela'), ('VERMELHA', 'Vermelha'), ('ESCASSEZ_HIDRICA', 'Escassez Hídrica'), ('DESCONHECIDA', 'Desconhecida')], default='DESCONHECIDA', max_length=20)),
                ('icms', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('outros_impostos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('linha_digitavel', models.CharField(blank=True, max_length=48)),
                ('codigo_de_barras', models.CharField(blank=True, max_length=44)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta de Energia',
                'verbose_name_plural': 'Contas de Energia',
                'db_table': 'bills',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='bills_user_id_e8d140_idx'), models.Index(fields=['period_start', 'period_end'], name='bills_period__4ab72b_idx'), models.Index(fields=['file_hash'], name='bills_file_ha_ce4825_idx')],
            },
        ),
    ]
