# Generated by Django 5.0.8 on 2025-08-18 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('region', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cpf_cnpj', models.CharField(max_length=18)),
                ('client_type', models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('contracted', 'Contratado'), ('active', 'Ativo'), ('inactive', 'Inativo')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18)),
                ('cep', models.CharField(max_length=9)),
                ('address', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=10)),
                ('complement', models.CharField(blank=True, max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='officers/contracts/')),
                ('dcmi_file', models.FileField(blank=True, null=True, upload_to='officers/dcmi/')),
                ('full_name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('mother_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='officers/documents/')),
                ('bank', models.CharField(max_length=100)),
                ('agency', models.CharField(max_length=10)),
                ('account', models.CharField(max_length=20)),
                ('pix', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributors', models.ManyToManyField(related_name='officers', to='energy.distributor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('consolidated_remuneration', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contracted_discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='financial/invoices/')),
                ('reference_month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='energy.client')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='energy.officer')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='energy.officer'),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_bill', models.FileField(blank=True, null=True, upload_to='quotes/bills/')),
                ('negative_certificate', models.FileField(blank=True, null=True, upload_to='quotes/certificates/')),
                ('installation_name', models.CharField(max_length=200)),
                ('installation_number', models.CharField(max_length=50)),
                ('consumption_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluída'), ('expired', 'Expirada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='energy.client')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.officer')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generator_name', models.CharField(max_length=200)),
                ('savings_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estimated_rebate_12_months', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity_term_days', models.IntegerField()),
                ('prior_notice_days', models.IntegerField()),
                ('contract_term_no_loyalty', models.BooleanField(default=True)),
                ('co2_reduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_best_proposal', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='energy.quote')),
            ],
        ),
    ]
